name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-64.0.dev <4.0.0'

dependencies:
  bloc: ^8.1.4
  date_format: ^2.0.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  url_launcher: ^6.2.6
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: JetBrains
      fonts:
        - asset: fonts/JetBrainsMono-Thin.ttf
          weight: 100
        - asset: fonts/JetBrainsMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/JetBrainsMono-ExtraLight.ttf
          weight: 200
        - asset: fonts/JetBrainsMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/JetBrainsMono-Light.ttf
          weight: 300
        - asset: fonts/JetBrainsMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/JetBrainsMono-Regular.ttf
        - asset: fonts/JetBrainsMono-Italic.ttf
          style: italic
        - asset: fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: fonts/JetBrainsMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: fonts/JetBrainsMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: fonts/JetBrainsMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/JetBrainsMono-ExtraBold.ttf
          weight: 800
        - asset: fonts/JetBrainsMono-ExtraBoldItalic.ttf
          weight: 800
          style: italic
